# Netlify configuration for Nuxt.js static site
[build]
  command = "npm run generate"
  publish = ".output/public"
  
[build.environment]
  NODE_VERSION = "18.20.8"
  NPM_VERSION = "10"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
